env: "dev" # также возможны: local, dev, prod
user: "noctusha"
pass: "noctushapass"
username: "username"
password: "password"
host: "localhost"
http_addr: ":8080"
port: 5432
name: "url-shortener"
max_conns: 5
min_conns: 2
timeout: 5s
redis_addr: "localhost:6379"
redis_db: 0